# Generated by Django 5.1.6 on 2025-04-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown Candidate', max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('score', models.IntegerField()),
                ('matched', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Default Position', max_length=255)),
                ('skills', models.TextField()),
                ('min_experience', models.IntegerField()),
                ('min_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
