# Generated by Django 5.1.6 on 2025-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='matched',
            field=models.BooleanField(),
        ),
    ]
