# Generated by Django 5.1.6 on 2025-05-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_candidate_education_candidate_email_and_more'),
        ('hrapp', '0004_alter_emailconfiguration_user'),
    ]

    operations = [
    ]
