# Generated by Django 5.2.6 on 2025-09-05 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0005_merge_20250519_0035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='match_percentage',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_text',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='matched',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, default='Unknown Candidate', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ResumeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('received_date', models.DateTimeField()),
                ('attachment_filename', models.CharField(max_length=255)),
                ('attachment_path', models.CharField(max_length=500)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['user', 'received_date'], name='hrapp_resum_user_id_81c968_idx'), models.Index(fields=['received_date'], name='hrapp_resum_receive_1fa0ee_idx'), models.Index(fields=['processed'], name='hrapp_resum_process_a6f849_idx')],
            },
        ),
    ]
